### ISSUE TITLE
Make Tracker dynamic

### ISSUE THREAD

**Issue by juddfranklin1** [juddfranklin1/eventful-widget#1]
- [ ] User should be prompted to choose a class (later element type or selector) that has events tracked on it.
- [ ] When user chooses a class, list of events with number of occurrences appears;
- [ ] User can then expand a given event and see details of each event.
